# Generated by Django 6.0.3 on 2026-08-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_email_auth_email_rename_id_auth_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
